version: '3'

services:
  database:
    image: mongo
    container_name: database
    environment:
      MONGO_INITDB_ROOT_USERNAME: test123
      MONGO_INITDB_ROOT_PASSWORD: test123
    ports:
      - 27017:27017
    networks:
      mongo-net:

  explorer:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: test123
      ME_CONFIG_MONGODB_ADMINPASSWORD: test123
      ME_CONFIG_MONGODB_URL: mongodb://test123:test123@database:27017/
    networks:
      mongo-net:

networks:
  mongo-net:
